[build]
  command = "npm run build:web"
  publish = "apps/web/.next"

[build.environment]
  HUSKY = "0"
  NODE_ENV = "production"
  NODE_VERSION = "22"
  NPM_FLAGS = "--include=dev"
  NPM_VERSION = "10"

[dev]
  command = "npm run dev:web"
  targetPort = 3001
  port = 8888
  framework = "#custom"
