[build]
  command = "npm run build:web"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "npm run dev:web"
  targetPort = 3001
  port = 8888
  framework = "#custom"
